# Generated by Django 3.1.12 on 2026-09-09 18:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('file_name', models.CharField(max_length=255)),
                ('file_path', models.CharField(help_text='Relative or storage path to PDF', max_length=500)),
                ('file_size_bytes', models.BigIntegerField(default=0)),
                ('total_pages', models.IntegerField(default=0)),
                ('extracted_pages_count', models.IntegerField(default=0)),
                ('extraction_mode', models.CharField(choices=[('auto', 'Auto (Extract All Immediately)'), ('manual', 'Manual (Extract Page-By-Page On Demand)')], default='auto', max_length=20)),
                ('status', models.CharField(choices=[('uploaded', 'Uploaded'), ('processing', 'Processing'), ('extracted', 'Extracted'), ('failed', 'Failed')], default='uploaded', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='users.tenant')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExtractedPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_number', models.IntegerField(help_text='1-indexed page number')),
                ('raw_text', models.TextField(blank=True, default='', help_text='Direct text extracted from PDF page')),
                ('ocr_text', models.TextField(blank=True, default='', help_text='Text extracted from embedded images via OCR')),
                ('combined_text', models.TextField(blank=True, default='', help_text='Raw text + appended OCR text')),
                ('has_images', models.BooleanField(default=False)),
                ('image_count', models.IntegerField(default=0)),
                ('word_count', models.IntegerField(default=0)),
                ('extracted_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='translation.document')),
            ],
            options={
                'ordering': ['document', 'page_number'],
                'unique_together': {('document', 'page_number')},
            },
        ),
        migrations.CreateModel(
            name='TokenUsageLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_type', models.CharField(max_length=50)),
                ('token_count', models.IntegerField(default=0)),
                ('source_lang', models.CharField(default='eng_Latn', max_length=32)),
                ('target_lang', models.CharField(default='hin_Deva', max_length=32)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='translation.document')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_logs', to='users.tenant')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='TranslatedPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_language', models.CharField(default='eng_Latn', max_length=32)),
                ('target_language', models.CharField(db_index=True, max_length=32)),
                ('translated_text', models.TextField()),
                ('tokens_used', models.IntegerField(default=0)),
                ('translated_at', models.DateTimeField(auto_now_add=True)),
                ('extracted_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='translation.extractedpage')),
            ],
            options={
                'ordering': ['extracted_page__page_number'],
                'unique_together': {('extracted_page', 'target_language')},
            },
        ),
    ]
