# Generated by Django 3.1.12 on 2026-09-09 18:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('translation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_number', models.IntegerField(help_text='1-indexed image index on page')),
                ('image_name', models.CharField(max_length=255)),
                ('image_path', models.CharField(help_text='Relative storage path', max_length=500)),
                ('image_url', models.CharField(help_text='Accessible media URL', max_length=500)),
                ('width', models.IntegerField(default=0)),
                ('height', models.IntegerField(default=0)),
                ('file_size_bytes', models.BigIntegerField(default=0)),
                ('ocr_text', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('extracted_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='translation.extractedpage')),
            ],
            options={
                'ordering': ['extracted_page', 'image_number'],
            },
        ),
    ]
